name: annotation-pipeline
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8.10
  - snakemake=6.4.1
  - samtools=1.12
  - picard=2.25.6
  - bwa=0.7.17
  - bcftools=1.12
  - bowtie2=2.4.4
  - trimmomatic=0.39
  - fastqc=0.11.9
  - multiqc=1.10.1
  - gatk=3.6
  - gatk4=4.2.0.0
  - bgzip=1.12
  - tabix=1.12